# Site settings
title: Yousef Hamza
email: jo.adam.93@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Yousef Hamza I'm Computer Engineering and Software Systems student
  and this is my blog!
  This blog is basically about my GSoC experience, and the things that interest me in
  general, new frameworks or technolgies, hope you find it entertaining.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jo_adam
github_username:  yousefhamza

# Build settings
markdown: kramdown
